---
name: BYU User Info - OAuth integration
description: Decorator around byu-user-info that makes it oauth-aware
resources:
  - src: dist/**
    dest: ./
entrypoints:
  byu-user-info-oauth.js: 'ES Module - OAuth User Sign In/Out Widget'
  byu-user-info-oauth.min.js: 'ES Module - Minified - OAuth User Sign In/Out Widget'
  byu-user-info-oauth.nomodule.js: 'No Module - OAuth User Sign In/Out Widget'
  byu-user-info-oauth.nomodule.min.js: 'No Module - Minified - OAuth User Sign In/Out Widget'
docs: https://github.com/byuweb/byu-user-info-oauth